spring:
  datasource:
    url: jdbc:mysql://mysql_tutor_talk:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create # JPA를 통해 Entity에 작성한대로 테이블 자동 생성 -> 배포 시 변경
    show-sql: true  # SQL 쿼리 로깅 활성화 -> 배포 시 변경
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info

external:
  welfare-api:
    url: ${WELFARE_API_BASE_URL}
    key: ${WELFARE_API_ENCODING_KEY}
