spring:
  datasource:
    url: jdbc:mysql://mysql_tutor_talk:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create # JPA? ?? Entity? ????? ??? ?? ?? -> ?? ? ??
    show-sql: true  # SQL ?? ?? ??? -> ?? ? ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info
